<a href="https://colab.research.google.com/github/mandaw34/DevinaAmanda_2411533009_ML2526/blob/main/praktikum3/TugasLogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
# Import library yang dibutuhkan
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [21]:
#load dataset
dataset_url = 'https://raw.githubusercontent.com/mandaw34/DevinaAmanda_2411533009_ML2526/refs/heads/main/praktikum2/Breast_cancer_data.csv'
df = pd.read_csv(dataset_url)
df.head()


,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,diagnosis
0,17.99,10.38,122.80,1001.0,0.11840,0
1,20.57,17.77,132.90,1326.0,0.08474,0
2,19.69,21.25,130.00,1203.0,0.10960,0
3,11.42,20.38,77.58,386.1,0.14250,0
4,20.29,14.34,135.10,1297.0,0.10030,0


In [22]:
X = df.drop("diagnosis", axis=1)
y = df["diagnosis"]

In [29]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.30,
    random_state=16
)

In [31]:
#Tugas A: Scalling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [35]:
#Tugaas B: Latih model yang sudah di scalling
model_scaling = LogisticRegression(max_iter=5000)
model_scaling.fit(X_train_scaled, y_train)
y_pred_scaling = model_scaling.predict(X_test_scaled)

#Tugas C: Prediksi dan evaluasi
print("Accuracy dengan scaling:", accuracy_score(y_test, y_pred_scaling))
print(confusion_matrix(y_test, y_pred_scaling))
print(classification_report(y_test, y_pred_scaling))

Accuracy dengan scaling: 0.9415204678362573
[[ 59   6]
 [  4 102]]
              precision    recall  f1-score   support

           0       0.94      0.91      0.92        65
           1       0.94      0.96      0.95       106

    accuracy                           0.94       171
   macro avg       0.94      0.93      0.94       171
weighted avg       0.94      0.94      0.94       171



In [24]:
#Tugas D: Model belum di scalling
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

model_no_scaling = LogisticRegression(max_iter=5000)

model_no_scaling.fit(X_train, y_train)

y_pred_no_scaling = model_no_scaling.predict(X_test)

print("Accuracy tanpa scaling:", accuracy_score(y_test, y_pred_no_scaling))
print(confusion_matrix(y_test, y_pred_no_scaling))
print(classification_report(y_test, y_pred_no_scaling))

Accuracy tanpa scaling: 0.9298245614035088
[[40  3]
 [ 5 66]]
              precision    recall  f1-score   support

           0       0.89      0.93      0.91        43
           1       0.96      0.93      0.94        71

    accuracy                           0.93       114
   macro avg       0.92      0.93      0.93       114
weighted avg       0.93      0.93      0.93       114



In [38]:
#Tugas E: Bandingkan beberapa thershold
y_prob = model_scaling.predict_proba(X_test_scaled)[:,1]

thresholds = [0.3, 0.5, 0.7]

for t in thresholds:

    y_pred_threshold = (y_prob >= t).astype(int)

    print("Threshold:", t)
    print("Accuracy:", accuracy_score(y_test, y_pred_threshold))
    print(confusion_matrix(y_test, y_pred_threshold))
    print(classification_report(y_test, y_pred_threshold))
    print("-----------------------")

Threshold: 0.3
Accuracy: 0.935672514619883
[[ 55  10]
 [  1 105]]
              precision    recall  f1-score   support

           0       0.98      0.85      0.91        65
           1       0.91      0.99      0.95       106

    accuracy                           0.94       171
   macro avg       0.95      0.92      0.93       171
weighted avg       0.94      0.94      0.93       171

-----------------------
Threshold: 0.5
Accuracy: 0.9415204678362573
[[ 59   6]
 [  4 102]]
              precision    recall  f1-score   support

           0       0.94      0.91      0.92        65
           1       0.94      0.96      0.95       106

    accuracy                           0.94       171
   macro avg       0.94      0.93      0.94       171
weighted avg       0.94      0.94      0.94       171

-----------------------
Threshold: 0.7
Accuracy: 0.9122807017543859
[[61  4]
 [11 95]]
              precision    recall  f1-score   support

           0       0.85      0.94      0.89    